spring:
  application:
    name: privileges_access
  datasource:
    url: jdbc:postgresql://localhost:5432/dpe1
    username: postgres
    password: Im@g!nnoVaTe
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
    ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8181